<script lang="ts">
  export let role:string; export let roleLabel:string; export let roleColor:string;
  type WorkItem={id:number;role:string;kind:string;title:string;status:string;priority:string;owner:string;counterparty:string;amount:number;created_at:string};
  type View='cockpit'|'queue'|'builder'|'handoffs';
  let view:View='cockpit',items:WorkItem[]=[],loading=true,title='',kind='',counterparty='',priority='medium',amount=0,notice='';
  const suites:Record<string,any>={
    orchestrator:{code:'OPS-01',headline:'Network command',sub:'Operate tenants, integrations, settlement and service health from one governed control surface.',score:'98.7%',scoreLabel:'network readiness',metrics:[['6','active organizations'],['12,480','events / 24h'],['99.98%','API success'],['$184k','open settlement']],modules:[['Tenant registry','Onboard banks and partners with control evidence','3 onboarding'],['Integration monitor','Signed events, retries and reconciliation','99.98% healthy'],['Settlement desk','Partner obligations, exceptions and approvals','$184k open'],['Incident room','Coordinated response and evidence','1 watch']],kinds:['Tenant onboarding','Integration change','Settlement run','Incident review'],parties:['Bank operations','Airline loyalty','Retail partner','Risk committee']},
    bank:{code:'BNK-10',headline:'Credit program operations',sub:'Configure approved products, run cohorts, route hardship and graduate successful customers.',score:'84.2%',scoreLabel:'completion forecast',metrics:[['4','live cohorts'],['8,420','active builders'],['97.1%','on-time rate'],['612','graduation ready']],modules:[['Product studio','Milestones, benefits, disclosures and limits','2 drafts'],['Cohort command','Enrollment, events and outcome tracking','4 live'],['Hardship router','Bank-approved options and consent','23 open'],['Graduation pipeline','Savings release and next-product review','612 ready']],kinds:['Product approval','Cohort launch','Hardship case','Graduation review'],parties:['Platform operator','Customer support','Risk committee','Partner manager']},
    customer:{code:'CB-2048',headline:'My credit journey',sub:'See what you owe, what you earned, what comes next, and where to get help.',score:'7 / 12',scoreLabel:'payments completed',metrics:[['$850','secured savings'],['3','benefits unlocked'],['149 days','to completion'],['100%','on-time streak']],modules:[['Payment progress','Schedule, confirmations and next due date','Next: 28 Aug'],['Benefit wallet','Earned airline and retail entitlements','3 available'],['Savings outcome','Restricted balance and maturity destination','$850'],['Support center','Options before a payment is missed','Help available']],kinds:['Payment question','Hardship support','Benefit issue','Privacy request'],parties:['Bank support','Partner support','Privacy team','Complaints team']},
    airline:{code:'AIR-22',headline:'Loyalty campaign studio',sub:'Fund targeted benefits, control inventory and prove incremental member and booking value.',score:'4.8×',scoreLabel:'campaign contribution ROAS',metrics:[['18,200','eligible members'],['2.4m','miles reserved'],['31%','activation'],['$42','cost / booking']],modules:[['Campaign builder','Milestones, audience, budget and capacity','3 campaigns'],['Inventory vault','Authorized miles, passes and status boosts','2.4m miles'],['Member activation','Consented enrollment and loyalty linkage','5,642 active'],['Attribution lab','Incremental booking and route contribution','4.8× ROAS']],kinds:['Campaign proposal','Inventory release','Redemption exception','Reconciliation review'],parties:['Bank partner team','Platform settlement','Airline finance','Risk committee']},
    retailer:{code:'RTL-18',headline:'Commerce partner studio',sub:'Design incremental offers, protect margin and connect credit progress to purchasing intent.',score:'$27.40',scoreLabel:'incremental basket uplift',metrics:[['12,600','eligible shoppers'],['38%','redemption'],['1.7×','repeat rate'],['24%','offer margin']],modules:[['Offer builder','Value, threshold, category and expiry','5 offers'],['Budget control','Funding caps and exposure by cohort','$96k remaining'],['Redemption pulse','Commerce events and exceptions','38% redeemed'],['Incrementality lab','Holdout lift, basket and repeat behavior','+$27.40 basket']],kinds:['Offer proposal','Budget release','Redemption exception','Attribution review'],parties:['Bank partner team','Platform settlement','Retail finance','Risk committee']},
    risk:{code:'RISK-00',headline:'Independent control plane',sub:'Approve, monitor, investigate, pause and evidence every customer-impacting capability.',score:'92 / 100',scoreLabel:'control effectiveness',metrics:[['7','approval gates'],['3','open cases'],['0','material breaches'],['100%','event traceability']],modules:[['Approval board','Product, disclosure, partner and change decisions','4 pending'],['Fairness monitor','Outcome parity and vulnerability signals','No breach'],['Case management','Complaints, privacy, incidents and remediation','3 open'],['Stop controls','Pause campaigns, cohorts or integrations','Armed']],kinds:['Approval decision','Fairness review','Complaint case','Stop action'],parties:['Bank product','Platform operator','Partner compliance','Executive committee']},
    investor:{code:'GROW-01',headline:'Enterprise value cockpit',sub:'Connect contracts, adoption, realized revenue, customer outcomes and expansion.',score:'$2.84m',scoreLabel:'contracted ARR',metrics:[['$2.84m','contracted ARR'],['121%','net retention'],['14 mo','CAC payback'],['68%','gross margin']],modules:[['Deal room','Bank and partner pipeline dependencies','$6.2m pipeline'],['Contract desk','Minimum commitments and obligations','5 active'],['Unit economics','Revenue, reward, service and infrastructure cost','68% margin'],['Expansion map','Cohorts, partners, modules and jurisdictions','3 next moves']],kinds:['Bank opportunity','Partner agreement','Pricing approval','Expansion review'],parties:['Bank executive','Partner executive','Finance team','Risk committee']}
  };
  $: suite=suites[role]; $: visible=items.filter(i=>i.role===role||i.counterparty.toLowerCase().includes(roleLabel.split(' ')[0].toLowerCase()));
  async function load(){loading=true;try{const r=await fetch('/api/work-items');if(r.ok)items=await r.json()}finally{loading=false}}
  async function create(){if(!title.trim())return;const res=await fetch('/api/work-items',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({role,kind:kind||suite.kinds[0],title,status:'open',priority,owner:roleLabel,counterparty:counterparty||suite.parties[0],amount})});if(res.ok){title='';amount=0;notice='Workflow created and handed off';await load();setTimeout(()=>notice='',2200)}}
  async function advance(item:WorkItem){const status=item.status==='open'?'in_review':item.status==='in_review'?'approved':'complete';await fetch(`/api/work-items/${item.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({status})});await load()}
  load();
</script>
<section class="suite-head" style={`--suite:${roleColor}`}><div><span>{suite.code} / ROLE WORKSPACE</span><h2>{suite.headline}</h2><p>{suite.sub}</p></div><div class="score"><strong>{suite.score}</strong><small>{suite.scoreLabel}</small><i>LIVE DEMO</i></div></section>
<div class="suite-nav">{#each [['cockpit','Cockpit'],['queue','Work queue'],['builder','Workflow builder'],['handoffs','Handoffs']] as n}<button class:active={view===n[0]} onclick={()=>view=n[0] as View}>{n[1]}</button>{/each}</div>
{#if view==='cockpit'}
 <div class="suite-metrics">{#each suite.metrics as m}<article><strong>{m[0]}</strong><span>{m[1]}</span></article>{/each}</div>
 <div class="module-grid">{#each suite.modules as m,i}<button onclick={()=>view=i===0?'builder':'queue'}><span>0{i+1}</span><i>↗</i><h3>{m[0]}</h3><p>{m[1]}</p><b>{m[2]}</b></button>{/each}</div>
 <div class="suite-activity"><div><span>OPERATING PULSE</span><h3>What needs attention now</h3></div>{#each visible.slice(0,3) as item}<article><i class={`p-${item.priority}`}></i><div><b>{item.title}</b><small>{item.kind} · {item.counterparty}</small></div><em>{item.status.replace('_',' ')}</em></article>{:else}<p class="empty">No open items. Create the first governed workflow.</p>{/each}</div>
{:else if view==='queue'}
 <div class="queue-head"><div><span>SHARED WORK QUEUE</span><h3>{roleLabel} operations</h3></div><button onclick={load}>REFRESH ↻</button></div><div class="work-table"><div class="tr labels"><span>WORK ITEM</span><span>COUNTERPARTY</span><span>PRIORITY</span><span>STATUS / ACTION</span></div>{#if loading}<p class="empty">Loading…</p>{:else}{#each visible as item}<div class="tr"><span><b>{item.title}</b><small>{item.kind} · #{item.id}</small></span><span>{item.counterparty}</span><span class={`priority p-${item.priority}`}>{item.priority}</span><span><button onclick={()=>advance(item)}>{item.status.replace('_',' ')} →</button></span></div>{:else}<p class="empty">Queue clear.</p>{/each}{/if}</div>
{:else if view==='builder'}
 <div class="builder-grid"><div class="form-card"><span>GOVERNED CREATION</span><h3>Create {roleLabel.toLowerCase()} workflow</h3><label>Workflow type<select bind:value={kind}><option value="">Select type</option>{#each suite.kinds as k}<option>{k}</option>{/each}</select></label><label>Purpose and outcome<input bind:value={title} placeholder="Describe the operational outcome"/></label><div class="two"><label>Counterparty<select bind:value={counterparty}><option value="">Select party</option>{#each suite.parties as p}<option>{p}</option>{/each}</select></label><label>Priority<select bind:value={priority}><option>low</option><option>medium</option><option>high</option><option>critical</option></select></label></div><label>Financial exposure / reference amount<input type="number" bind:value={amount} min="0"/></label><button class="primary" onclick={create}>CREATE & HAND OFF →</button>{#if notice}<p class="notice">✓ {notice}</p>{/if}</div><div class="guard-card"><span>AUTOMATIC CONTROL ENVELOPE</span><h3>Evidence before action</h3>{#each ['Named accountable owner','Explicit counterparty','Versioned status history','Priority and exposure signal','Independent review path','Audit-ready timestamp'] as g}<p><i>✓</i>{g}</p>{/each}<div><b>Prototype boundary</b><small>This coordinates work. It does not execute a loan decision, money movement, credit report, or live benefit issuance.</small></div></div></div>
{:else}
 <div class="handoff-map"><div class="current" style={`--suite:${roleColor}`}><small>YOU ARE HERE</small><b>{roleLabel}</b><span>{suite.code}</span></div>{#each Object.entries(suites).filter(([k])=>k!==role) as [key,s],i}<button onclick={()=>{counterparty=s.headline;view='builder'}} class={`h${i+1}`}><i>{s.code.split('-')[0]}</i><span>{s.headline}</span><small>{items.filter(x=>x.role===key).length} operating records</small></button>{/each}<svg viewBox="0 0 800 400" aria-hidden="true"><path d="M400 200 L110 70 M400 200 L400 45 M400 200 L690 70 M400 200 L690 330 M400 200 L400 355 M400 200 L110 330"/></svg></div>
{/if}
